FROM golang AS builder
WORKDIR /frp
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN make -f Makefile.cross-compiles

FROM arm64v8/alpine
WORKDIR /
COPY --from=builder /frp/frps_linux_arm64 /usr/local/bin/frps
COPY --from=builder /frp/conf/frps.ini /etc/frps.ini
EXPOSE 7000 7500
CMD ["frps", "--config", "/etc/frps.ini"]
