FROM golang AS builder
WORKDIR /frp
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN make frps_linux_arm

FROM arm32v7/alpine
WORKDIR /
COPY --from=builder /frp/bin/frps_linux_arm /usr/local/bin/frps
COPY --from=builder /frp/conf/frps.ini /etc/frps.ini
EXPOSE 7000 7500
CMD ["frps", "--config", "/etc/frps.ini"]
